#!/bin/bash
# Alternative: Extend sudo password timeout (keeps security, reduces prompts)

set -e

echo "========================================="
echo "Sudo Password Timeout Extension"
echo "========================================="
echo ""
echo "This extends how long sudo remembers your password."
echo "More secure than passwordless sudo, but still convenient."
echo ""

SUDOERS_FILE="/etc/sudoers.d/sudo-timeout"
USERNAME=$(whoami)

# Ask for timeout duration
echo "How long should sudo remember your password?"
echo "  - 30 minutes (recommended)"
echo "  - 60 minutes"
echo "  - 120 minutes (2 hours)"
echo "  - 240 minutes (4 hours)"
echo ""
read -p "Enter timeout in minutes [30]: " timeout
timeout=${timeout:-30}

echo ""
echo "Setting sudo timeout to $timeout minutes for user: $USERNAME"
echo ""

# Create sudoers file
sudo tee "$SUDOERS_FILE" > /dev/null <<EOF
# Extend sudo password timeout for $USERNAME
# Generated by setup-sudo-timeout.sh

Defaults:$USERNAME timestamp_timeout=$timeout
EOF

echo "✓ Created sudoers file: $SUDOERS_FILE"

# Verify syntax
if sudo visudo -c -f "$SUDOERS_FILE"; then
    echo "✓ Sudoers file syntax is valid"
else
    echo "✗ Error: Sudoers file has syntax errors!"
    exit 1
fi

echo ""
echo "========================================="
echo "Setup complete!"
echo "========================================="
echo ""
echo "Sudo will now remember your password for $timeout minutes."
echo "After entering your password once, you won't be prompted again"
echo "for $timeout minutes."
echo ""
echo "This is more secure than passwordless sudo while still being convenient."
echo ""


