#!/bin/bash
# Setup passwordless sudo for content-manager service commands

set -e

echo "Setting up passwordless sudo for content-manager commands..."
echo ""

SUDOERS_FILE="/etc/sudoers.d/content-manager"
USERNAME=$(whoami)

# Create sudoers file
sudo tee "$SUDOERS_FILE" > /dev/null <<EOF
# Allow passwordless sudo for content-manager service management
# Generated by setup-passwordless-sudo.sh

$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl start content-manager.service
$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl stop content-manager.service
$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl restart content-manager.service
$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl status content-manager.service
$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl enable content-manager.service
$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl disable content-manager.service
$USERNAME ALL=(ALL) NOPASSWD: /bin/systemctl daemon-reload
$USERNAME ALL=(ALL) NOPASSWD: /usr/bin/journalctl -u content-manager.service*
$USERNAME ALL=(ALL) NOPASSWD: /bin/cp /home/$USERNAME/content-manager/content-manager.service /etc/systemd/system/
EOF

echo "✓ Created sudoers file: $SUDOERS_FILE"

# Verify syntax
if sudo visudo -c -f "$SUDOERS_FILE"; then
    echo "✓ Sudoers file syntax is valid"
else
    echo "✗ Error: Sudoers file has syntax errors!"
    exit 1
fi

echo ""
echo "========================================="
echo "Setup complete!"
echo "========================================="
echo ""
echo "You can now use these commands without a password:"
echo "  sudo systemctl start content-manager.service"
echo "  sudo systemctl stop content-manager.service"
echo "  sudo systemctl restart content-manager.service"
echo "  sudo systemctl status content-manager.service"
echo "  sudo systemctl daemon-reload"
echo "  sudo journalctl -u content-manager.service -f"
echo ""
echo "Test it:"
echo "  sudo -n systemctl status content-manager.service"
echo ""


