#!/bin/bash
# Setup global passwordless sudo for all commands
# WARNING: This reduces security. Only use if you understand the risks.

set -e

echo "========================================="
echo "Global Passwordless Sudo Setup"
echo "========================================="
echo ""
echo "WARNING: This will allow ALL sudo commands without a password."
echo "This is convenient but reduces security."
echo ""
read -p "Do you want to continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

SUDOERS_FILE="/etc/sudoers.d/passwordless-sudo"
USERNAME=$(whoami)

echo ""
echo "Setting up passwordless sudo for user: $USERNAME"
echo ""

# Create sudoers file
sudo tee "$SUDOERS_FILE" > /dev/null <<EOF
# Allow passwordless sudo for $USERNAME
# WARNING: This allows all sudo commands without password
# Generated by setup-global-passwordless-sudo.sh

$USERNAME ALL=(ALL) NOPASSWD: ALL
EOF

echo "✓ Created sudoers file: $SUDOERS_FILE"

# Verify syntax
if sudo visudo -c -f "$SUDOERS_FILE"; then
    echo "✓ Sudoers file syntax is valid"
else
    echo "✗ Error: Sudoers file has syntax errors!"
    exit 1
fi

echo ""
echo "========================================="
echo "Setup complete!"
echo "========================================="
echo ""
echo "You can now use ALL sudo commands without a password:"
echo "  sudo systemctl ..."
echo "  sudo apt install ..."
echo "  sudo cp ..."
echo "  sudo nano ..."
echo "  (any sudo command)"
echo ""
echo "Test it:"
echo "  sudo -n whoami"
echo ""
echo "To remove this later, delete the file:"
echo "  sudo rm $SUDOERS_FILE"
echo ""


